import { MangaItem } from './types';

export const mockMangaData: MangaItem[] = [
  {
    id: 1,
    title: "Jujutsu Kaisen",
    author: "Gege Akutami",
    coverImage: "https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg",
    rating: "4.9",
    latestChapter: "243",
    genres: ["Action", "Supernatural", "School"],
    description: "Yuji Itadori is an unnaturally fit high school student living a normal life. But when he consumes the finger of a legendary demon, he becomes the host of Sukuna and gets thrown into the world of Jujutsu Sorcery.",
  },
  {
    id: 2,
    title: "Chainsaw Man",
    author: "Tatsuki Fujimoto",
    coverImage: "https://images.pexels.com/photos/1193743/pexels-photo-1193743.jpeg",
    rating: "4.8",
    latestChapter: "156",
    genres: ["Action", "Horror", "Supernatural"],
  },
  {
    id: 3,
    title: "One Piece",
    author: "Eiichiro Oda",
    coverImage: "https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg",
    rating: "4.9",
    latestChapter: "1091",
    genres: ["Adventure", "Fantasy", "Comedy"],
  },
  {
    id: 4,
    title: "Solo Leveling",
    author: "Chugong",
    coverImage: "https://images.pexels.com/photos/1142950/pexels-photo-1142950.jpeg",
    rating: "4.7",
    latestChapter: "179",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 5,
    title: "My Hero Academia",
    author: "Kohei Horikoshi",
    coverImage: "https://images.pexels.com/photos/1374910/pexels-photo-1374910.jpeg",
    rating: "4.6",
    latestChapter: "402",
    genres: ["Action", "School", "Superhero"],
  },
  {
    id: 6,
    title: "Demon Slayer",
    author: "Koyoharu Gotouge",
    coverImage: "https://images.pexels.com/photos/1429748/pexels-photo-1429748.jpeg",
    rating: "4.8",
    latestChapter: "205",
    genres: ["Action", "Supernatural", "Historical"],
  },
  {
    id: 7,
    title: "Tower of God",
    author: "SIU",
    coverImage: "https://images.pexels.com/photos/1707820/pexels-photo-1707820.jpeg",
    rating: "4.7",
    latestChapter: "570",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 8,
    title: "The Beginning After The End",
    author: "TurtleMe",
    coverImage: "https://images.pexels.com/photos/2179483/pexels-photo-2179483.jpeg",
    rating: "4.8",
    latestChapter: "189",
    genres: ["Adventure", "Fantasy", "Romance"],
  },
  {
    id: 9,
    title: "Omniscient Reader",
    author: "Sing Shong",
    coverImage: "https://images.pexels.com/photos/3618162/pexels-photo-3618162.jpeg",
    rating: "4.9",
    latestChapter: "156",
    genres: ["Action", "Fantasy", "Drama"],
  },
  {
    id: 10,
    title: "Black Clover",
    author: "Yūki Tabata",
    coverImage: "https://images.pexels.com/photos/4446794/pexels-photo-4446794.jpeg",
    rating: "4.5",
    latestChapter: "367",
    genres: ["Action", "Comedy", "Fantasy"],
  },
  {
    id: 11,
    title: "Dr. Stone",
    author: "Riichiro Inagaki",
    coverImage: "https://images.pexels.com/photos/1563356/pexels-photo-1563356.jpeg",
    rating: "4.7",
    latestChapter: "232",
    genres: ["Adventure", "Sci-Fi", "Comedy"],
  },
  {
    id: 12,
    title: "The God of High School",
    author: "Yongje Park",
    coverImage: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg",
    rating: "4.6",
    latestChapter: "529",
    genres: ["Action", "Martial Arts", "Supernatural"],
  },
  {
    id: 13,
    title: "Vinland Saga",
    author: "Makoto Yukimura",
    coverImage: "https://images.pexels.com/photos/1939485/pexels-photo-1939485.jpeg",
    rating: "4.9",
    latestChapter: "201",
    genres: ["Action", "Adventure", "Historical"],
  },
  {
    id: 14,
    title: "Attack on Titan",
    author: "Hajime Isayama",
    coverImage: "https://images.pexels.com/photos/1762851/pexels-photo-1762851.jpeg",
    rating: "4.9",
    latestChapter: "139",
    genres: ["Action", "Drama", "Fantasy"],
  },
  {
    id: 15,
    title: "Spy x Family",
    author: "Tatsuya Endo",
    coverImage: "https://images.pexels.com/photos/2832432/pexels-photo-2832432.jpeg",
    rating: "4.7",
    latestChapter: "87",
    genres: ["Action", "Comedy", "Slice of Life"],
  },
  {
    id: 16,
    title: "Bleach",
    author: "Tite Kubo",
    coverImage: "https://images.pexels.com/photos/2850820/pexels-photo-2850820.jpeg",
    rating: "4.6",
    latestChapter: "686",
    genres: ["Action", "Adventure", "Supernatural"],
  },
  {
    id: 17,
    title: "Naruto",
    author: "Masashi Kishimoto",
    coverImage: "https://images.pexels.com/photos/1777479/pexels-photo-1777479.jpeg",
    rating: "4.8",
    latestChapter: "700",
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 18,
    title: "Dragon Ball Super",
    author: "Akira Toriyama",
    coverImage: "https://images.pexels.com/photos/3738097/pexels-photo-3738097.jpeg",
    rating: "4.5",
    latestChapter: "98",
    genres: ["Action", "Adventure", "Comedy"],
  }
];

export const mockChapterImages: string[] = [
  "https://images.pexels.com/photos/2646531/pexels-photo-2646531.jpeg",
  "https://images.pexels.com/photos/2820884/pexels-photo-2820884.jpeg",
  "https://images.pexels.com/photos/1530701/pexels-photo-1530701.jpeg",
  "https://images.pexels.com/photos/2486168/pexels-photo-2486168.jpeg",
  "https://images.pexels.com/photos/4151484/pexels-photo-4151484.jpeg",
  "https://images.pexels.com/photos/2982449/pexels-photo-2982449.jpeg",
];

export const categories = [
  { id: 'all', name: 'All' },
  { id: 'action', name: 'Action' },
  { id: 'adventure', name: 'Adventure' },
  { id: 'comedy', name: 'Comedy' },
  { id: 'drama', name: 'Drama' },
  { id: 'fantasy', name: 'Fantasy' },
  { id: 'horror', name: 'Horror' },
  { id: 'mystery', name: 'Mystery' },
  { id: 'romance', name: 'Romance' },
  { id: 'sci-fi', name: 'Sci-Fi' },
  { id: 'slice-of-life', name: 'Slice of Life' },
  { id: 'supernatural', name: 'Supernatural' },
];